import Head from "next/head";
import React, { useState } from "react";
// import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";

const Home = () => {
  // const inter = Inter({ subsets: ["latin"] });
  let nav_list = [
    "nav1",
    "nav2",
    "nav3",
    "nav4",
    "nav5",
    "nav6",
    "nav7",
    "nav8",
  ];
  const [site, setSite] = useState(0);
  const position = { transform: `translate(${site}%,0%)` };
  const front = () => {
    console.log(site);
    if (site < 0) {
      setSite((prevSite) => prevSite + 15);
    }
  };
  const next = () => {
    console.log(site);
    if (site > -60) {
      setSite((prevSite) => prevSite - 15);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <div>
          <button className={styles.left} onClick={front}>
            w
          </button>
          <ul className={styles.ul} style={position}>
            {nav_list.map((title: string) => {
              return (
                <li className={styles.li} key={title}>
                  {title}
                  <div className={styles.nav_border}></div>
                </li>
              );
            })}
          </ul>
          <button className={styles.right} onClick={next}>
            w
          </button>
        </div>
      </nav>
    </>
  );
};
export default Home;
